# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/oshwa" # the subpath of your site, e.g. /blog
url: "http://objectively.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
seo_image_path: #'/images/media/filename.jpg'

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json

timezone: America/New_York

# Folder Structure
source: ./source
sass:
    style: compressed

contentful:
  spaces:
    - basicsPage: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: basicsPage
    - certificationPage: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: certificationPage
    - exemplarProject: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: exemplarProject
    - learningModule: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: learningModule
    - license: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: license
    - processPage: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: processPage
    - project: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: project
    - questions: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: questions
    - spectrumItem: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: spectrumItem
    - faqPage: # Jekyll _data folder identifier - Required
        space: ENV_OSHWA_CONTENTFUL_SPACE_ID         # Required
        access_token: ENV_OSHWA_CONTENTFUL_DELIVERY_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: /contentful # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: faqPage

page_gen:
  - data: 'contentful.project.project'
    template: 'profile_template'
    name: 'oshwa_uid'
    dir: 'profile'
  - data: 'contentful.exemplarProject.exemplarProject'
    template: 'exemplar_template'
    name: 'project_uid'
    dir: 'exemplar'
