version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run: gem install bundler --pre
      - run: bundle install
      - run: npm install
      - run: bash automated_build.sh
  test:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout:
          path: ~/oshwa-certification
      - run: echo "done"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test
